# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/leonardo/Desktop/artico_spider/artico3/demos/flexible_GSZIE_matmul/build.hw/xczu9eg.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_reset_0_0/system_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_reset_0_0 || ORIG_REF_NAME==system_reset_0_0}]

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0}]

# IP: bd/system/ip/system_artico3_shuffler_0_0/system_artico3_shuffler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_artico3_shuffler_0_0 || ORIG_REF_NAME==system_artico3_shuffler_0_0}]

# IP: bd/system/ip/system_a3_slot_0_0/system_a3_slot_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_0_0 || ORIG_REF_NAME==system_a3_slot_0_0}]

# IP: bd/system/ip/system_a3_slot_1_0/system_a3_slot_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_1_0 || ORIG_REF_NAME==system_a3_slot_1_0}]

# IP: bd/system/ip/system_a3_slot_2_0/system_a3_slot_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_2_0 || ORIG_REF_NAME==system_a3_slot_2_0}]

# IP: bd/system/ip/system_a3_slot_3_0/system_a3_slot_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_3_0 || ORIG_REF_NAME==system_a3_slot_3_0}]

# IP: bd/system/ip/system_a3_slot_4_0/system_a3_slot_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_4_0 || ORIG_REF_NAME==system_a3_slot_4_0}]

# IP: bd/system/ip/system_a3_slot_5_0/system_a3_slot_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_5_0 || ORIG_REF_NAME==system_a3_slot_5_0}]

# IP: bd/system/ip/system_a3_slot_6_0/system_a3_slot_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_6_0 || ORIG_REF_NAME==system_a3_slot_6_0}]

# IP: bd/system/ip/system_a3_slot_7_0/system_a3_slot_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_a3_slot_7_0 || ORIG_REF_NAME==system_a3_slot_7_0}]

# IP: bd/system/ip/system_axi_a3ctrl_0/system_axi_a3ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_a3ctrl_0 || ORIG_REF_NAME==system_axi_a3ctrl_0}]

# IP: bd/system/ip/system_axi_a3data_0/system_axi_a3data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_a3data_0 || ORIG_REF_NAME==system_axi_a3data_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_auto_ds_1/system_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_1 || ORIG_REF_NAME==system_auto_ds_1}]

# IP: bd/system/ip/system_auto_ds_0/system_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/system_ooc.xdc
